version: '3.8'

services:
  web:
    build: .
    ports:
      - "5777:5777"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./instance:/var/lib/sqlite
