"""empty message

Revision ID: 25498b80be16
Revises: 5927d6da5ffa
Create Date: 2024-06-19 23:32:16.787010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25498b80be16'
down_revision = '5927d6da5ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('_is_active')

    # ### end Alembic commands ###
