"""empty message

Revision ID: 7e431996e441
Revises: 82c82a855b03
Create Date: 2024-06-19 19:41:33.146375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e431996e441'
down_revision = '82c82a855b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_page_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('public_page_content', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
