"""empty message

Revision ID: d1d3e95b83c6
Revises: 25498b80be16
Create Date: 2024-06-23 14:58:12.684405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d3e95b83c6'
down_revision = '25498b80be16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_page_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('text_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_page_content', schema=None) as batch_op:
        batch_op.drop_column('text_color')
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###
